### ISSUE TITLE
How should I proceed with preprocessing after ATISS using preprocess_TDFront.py?

### ISSUE THREAD

**Issue by mahmutyasiresmek** [QiuhongAnnaWei/LEGO-Net#6]
I have completed the preprocessing using the ATISS script on 3D-front data, and now I would like to continue by generating processed_livingroom_augmented files using the preprocess_TDFront.py script. Could you please provide guidance on how to do this?

**Comment by QiuhongAnnaWei** [comment]
Sorry for the late response!

If you would to create a non-augmented version (e.g., folders `processed_bedroom` and `processed_livingroom` in the downloadable zip on the Google Drive), uncomment [this section](https://github.com/QiuhongAnnaWei/LEGO-Net/blob/main/data/preprocess_TDFront.py#L365-L373). 

If you would to create an augmented version (e.g., folders `processed_bedroom_augmented` and `processed_livingroom_augmented` in the downloadable zip on the Google Drive), uncomment [this section](https://github.com/QiuhongAnnaWei/LEGO-Net/blob/main/data/preprocess_TDFront.py#L380-L390).
