### ISSUE TITLE
data issue

### ISSUE THREAD

**Issue by zhaockab** [QiuhongAnnaWei/LEGO-Net#7]
Hello, that's a great job. And I want to use your code on my own task. But I don't know the dataset meaning. Could you please provide a detailed description of the angles, class_labels, floor_planboundary_points_normals, floor_plan_centroid, floor_plan_faces, floor_plan_ordered_corners, floor_plan_vertices, jids, json_path, remapped_room_layout, room_layout, scene_id in the dataset.

**Comment by QiuhongAnnaWei** [comment]
Hi, so sorry for the late response!

Most of the properties you mentioned come from [ATISS](https://github.com/nv-tlabs/ATISS). 

As for items I created, here are some comments useful for understanding `floor_plan_boundary_points_normals` and `floor_plan_ordered_corners`: 

- https://github.com/QiuhongAnnaWei/LEGO-Net/blob/main/data/TDFront.py#L427
- https://github.com/QiuhongAnnaWei/LEGO-Net/blob/main/train.py#L591

`remapped_room_layout` is a remapped version of `room_layout` to correct for some scaling offsets. See https://github.com/QiuhongAnnaWei/LEGO-Net/blob/main/data/preprocess_TDFront.py#L162.
